server:
  port: 9001
  
spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/
      
#removing because it will load from bootstrap.yml    
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296
#removing because it will load from cloud-config 
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost  
  
 